### ISSUE TITLE
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

### ISSUE THREAD

**Issue by ctsrc** [geeekpi/absminitowerkit#2]
Hi, I have a 52Pi Raspberry Pi Mini Tower NAS Kit ZP-0130

The OLED display on the front of the case works perfectly as it should

The fan works perfectly as it should for cooling, but does not glow any color

When I try the neopixel examples, I get:

```text
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
```

**Comment by yoyojacky** [comment]
Thanks for paul.jackson 's advice ,  he found a new solution : 
The solotion was found at:
 
https://github.com/rpi-ws281x/rpi-ws281x-python/blob/master/library/README.rst
 
specifically the section dealing with Limitations, specifically PWM.
 
This solved his problem......
 
PWM
Since this library and the onboard Raspberry Pi audio both use the PWM, they cannot be used together. You will need to blacklist the Broadcom audio kernel module by creating a file /etc/modprobe.d/snd-blacklist.conf with

blacklist snd_bcm2835
If the audio device is still loading after blacklisting, you may also need to comment it out in the /etc/modules file.

On headless systems you may also need to force audio through hdmi Edit config.txt and add:

hdmi_force_hotplug=1
hdmi_force_edid_audio=1
A reboot is required for this change to take effect

Some distributions use audio by default, even if nothing is being played. If audio is needed, you can use a USB audio device instead.

 

Blacklisting my sound did the trick, as soon as I changed that and the system rebooted got RAINBOW and it continued.....downside I have lost my Audio thru the jack but have it on the HDMI, albeit not as Loud as I would like.  Am going to try a USB sound device to see if that is a possilbity and if not I will Hashtag the Blacklist file and live with the starburst for a while and change back when finished.....

**Comment by yoyojacky** [comment]
> Hi, I have a 52Pi Raspberry Pi Mini Tower NAS Kit ZP-0130
> 
> The OLED display on the front of the case works perfectly as it should
> 
> The fan works perfectly as it should for cooling, but does not glow any color
> 
> When I try the neopixel examples, I get:
> 
> ```
> RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
> ```
Could you please post your OS type? and version?
